version: "3.7"
services:
  app:
    image: node_todo
    restart: always
    container_name: node_todo
    build: .
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
    driver: bridge
