name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.13.0'
  NODE_ENV: $NODE_ENV
  PORT: $PORT
  MYSQL_HOST: $MYSQL_HOST
  MYSQL_DBNAME: $MYSQL_DBNAME
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASSWORD
  MYSQL_PORT: $MYSQL_PORT
  MYSQL_DRIVER: $MYSQL_DRIVER
  
jobs:
  deploy:
    runs-on: self-hosted
            
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Environtment
        run: |
          touch .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "" >> .env
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
          echo "MYSQL_DBNAME=${{ secrets.MYSQL_DBNAME }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> .env
          echo "MYSQL_DRIVER=${{ secrets.MYSQL_DRIVER }}" >> .env

      - name: dockerize
        run: |
          docker compose up -d --build
