name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.13.0'
  MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  MYSQL_DBNAME: ${{ secrets.MYSQL_DBNAME }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
  MYSQL_DRIVER: ${{ secrets.MYSQL_DRIVER }}
  
jobs:
  deploy:
    runs-on: self-hosted
            
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: dockerize
        run: |
          docker compose up -d --build
